Fix CUP version conflict(i.e. xalan.jar) in some environment.
As different version of JavaCup libraries are bundled by several other
libraries (i.e. xalan), there has been such problems like
NoSuchMethodError thrown in certain environment depending on library
orders in the runtime classpath.

This change eliminate such a problem by adding certain methods to
CupParser class which are not present in an earlier version of JavaCup
library.